### ISSUE TITLE
hard to read namespace qualifiers and externs (C++)

### ISSUE THREAD

**Issue by izirku** [catppuccin/visual-studio#30] opened 2023-06-24 01:16 UTC
I must say I do like the theme a lot, however, there are some issues with C++ code:

![image](https://github.com/catppuccin/visual-studio/assets/1328365/3d318287-4e03-4203-bf58-35fd3aa76747)

Also, there is a noticeable flash of "un-highlighted" code syntax before it gets highlighted by the theme. Is this something that is un-avoidable due to the way VS themes work or is it something that can be fixed?

ty for your work btw!

**Comment by izirku** [comment] 2023-06-27 18:20
@djflan , thank you for getting back on this!

I'm on Catppuccin 1.4.8, trying to use mocha, on latest VS2022.

Right, so, I have ReSharper 2023.1.2 extension that could be interfering (will check on this), only other extension that deals with input/editor is VsVim 2022, but I don't think this one does any interference, however, I'll check on that too.

**Comment by djflan** [comment] 2023-06-30 14:25
@izirku You might want to look into VsVim - I think we had someone else using this that reported odd colorization. I don't use vim at all, so don't test against it. I'm pretty sure the VS extension does some custom coloring. Some of that might have been included in the themes - we could remove those entries and let that extension set whatever defaults are required.

**Comment by 0xBLAHAJ** [comment] 2023-08-11 21:41
This is an issue with ReSharper; a fix that worked for me was editing this setting:
Extensions > ReSharper > Options > C++ (Under the Code Editing tab) > Inspections > Untick 'Color Identifiers' then Save

**Comment by djflan** [comment] 2023-10-21 19:16
@izirku I am unable to reproduce this behavior. For now, I will close this issue - if it still persists, you may reopen this or a new issue.

**Closed by djflan** 2023-10-21 19:16 UTC
