### ISSUE TITLE
Arrows Are Not Themed

### ISSUE THREAD

**Issue by kryzet** [catppuccin/visual-studio#64] opened 2024-12-06 16:19 UTC
In code, Visual Studio shows arrow buttons for collapsing regions of code/comments. When using the Dark theme, the buttons appear dark, and when using the Light theme, they appear light. However, the Catppuccin theme doesn't seem to color the arrows correctly, leaving them light in a way that is not even consistent with Latte.

**Comment by sgoudham** [comment] 2024-12-06 16:23
I think this is a duplicate of #60, feel free to re-open if it's not.
The latest commit has the fix for that issue but still needs to be published to the Visual Studio Marketplace iirc

**Closed by sgoudham** 2024-12-06 16:23 UTC
