### ISSUE TITLE
VS 2022 text color doesn't change

### ISSUE THREAD

**Issue by vkosciuszko** [catppuccin/visual-studio#51] opened 2024-05-14 18:58 UTC
Hello,

for some reason when I enable the theme I only get the background, the color of the code is still the default "dark" from MS (light for the latte variant). 

<img width="1066" alt="Capture d'écran 2024-05-14 205826" src="https://github.com/catppuccin/visual-studio/assets/27742874/d6f1a5e3-5c5e-4f60-951b-74db4e174c3f">

**Comment by djflan** [comment] 2024-05-18 12:10
I can't reproduce this behavior on my end. Closing this for now, but if you find a series of steps that always result in the same outcome here, please reopen the issue.

**Closed by djflan** 2024-05-18 12:10 UTC
